/**
 * useCMEData Hook
 * Fetches CME data from JSON files (generated by pipeline)
 * Polls every 30 seconds when tab is active
 */

import { useState, useEffect } from 'react'

const POLL_INTERVAL = 30 * 1000 // 30 seconds

export function useCMEData(isActive) {
  const [queue, setQueue] = useState(null)
  const [classification, setClassification] = useState(null)
  const [positions, setPositions] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (!isActive) return

    async function fetchData() {
      try {
        // Fetch all three JSON files in parallel
        const [queueRes, classRes, posRes] = await Promise.all([
          fetch(`data/cme_queue.json?t=${Date.now()}`),
          fetch(`data/cme_classification.json?t=${Date.now()}`),
          fetch(`data/cme_positions.json?t=${Date.now()}`)
        ])

        const queueData = queueRes.ok ? await queueRes.json() : null
        const classData = classRes.ok ? await classRes.json() : null
        const posData = posRes.ok ? await posRes.json() : null

        setQueue(queueData)
        setClassification(classData)
        setPositions(posData)
        setError(null)
        setLoading(false)
      } catch (e) {
        console.warn('CME data fetch failed:', e)
        setError(e.message)
        setLoading(false)
      }
    }

    fetchData()
    const interval = setInterval(fetchData, POLL_INTERVAL)
    
    return () => clearInterval(interval)
  }, [isActive])

  return {
    queue,
    classification,
    positions,
    loading,
    error
  }
}
